### ISSUE TITLE
Rakshasa: Wrong recipe

### ISSUE THREAD

**Issue by LeonardoValente** [arantius/persona-fusion-calculator#14]
This appears at rakshasa page:

23 | 16,089 ¥ | Archangel (10 / Justice) | Inugami (10 / Hanged Man) | Alp (6 / Lovers)

However, it results in fortuna

**Comment by arantius** [comment]
So first, I think you're referring to:

https://arantius.github.io/persona-fusion-calculator/3fes.html#/persona/Rakshasa

Second: Your inputs are at exactly that level, or perhaps higher?

**Comment by LeonardoValente** [comment]
I searched a little bit about logic behind fusion and i one of my personas is overleveled. Sorry about that

**Comment by arantius** [comment]
So there's a couple possibilities.  That combo relies on the Arcana order to break the tie of the level 10 personas; Justice is lower than Hanged.  So the triangle combo is:

1. Lovers/6 + Hanged/10 = Hermit/9
2. Hermit/9 + Justice/10 = Strength/13
3. Rakshasa!

If we get that backwards, it's:

1. Lovers/6 + Justice/10 = Chariot/9
2. Chariot/9 + Hanged/10 = Fortune/13
3. Fortuna!

So I'm guessing your Inugami was at least level 11?

**Comment by LeonardoValente** [comment]
Yeah, inugami was level 13, that's why i closed the issue. Thanks for the
awnser anyway =)

Em Dom, 10 de mar de 2019 17:07, arantius <notifications@github.com>
escreveu:
