### ISSUE TITLE
P4G Fusion Result Correctness

### ISSUE THREAD

**Issue by studentism** [arantius/persona-fusion-calculator#15]
Your resource has been quite helpful, and I'm incredibly grateful for the work you put into it. However, I've come across a couple discrepancies. One example:

From the recipe page for [Vetala](https://arantius.github.io/persona-fusion-calculator/4golden.html#/persona/Vetala)

#38 Ghoul (9 / Death) | Orobas (8 / Magician) | Valkyrie (8 / Strength)

The combination does not create a Vetala.

![novetala](https://user-images.githubusercontent.com/142393/85659507-7771f600-b669-11ea-9a53-761ac9cd7a47.PNG)

It's also possible the fusion results on the Steam P4G release are different. Out of curiosity, was the data mined or compiled from results? (I've save scumming fusions, so it's not a _huge_ deal, just figured I should mention it.)

**Comment by arantius** [comment]
The screenshot shows your Orobas is level 12, not 8.  This is significant.  3-way fusions are ordered by level, the lower two are combined first, then the highest level one.  The app assumes you're doing 

8/Strength + 8/Magician = 17/Justice plus 17/Justice + 9/Death = 14/Devil

But you're doing:

9/Strength + 9/Death = 10/Hanged plus 10/Hanged + 12/Magician = 12/Fortune

The lowest level fortune above 12 is ... Fortuna!

https://gamefaqs.gamespot.com/ps2/945498-shin-megami-tensei-persona-4/map/5911-fusion-chart

**Comment by studentism** [comment]
Thank you so very much for taking the time to explain this, I feel like an idiot now, haha. Hopefully this doesn't re-open the ticket. Take care of yourself!
